version: "3.8"

services:
  web:
    build: .
    restart: always
    entrypoint: sh
    command: startscript.sh
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - EMAIL_HOST=yourhost@gmail.com
      - EMAIL_PASSWORD=xxx
      - PG_HOST=db
      - PG_PORT=5432
      - PG_NAME=finproj
      - PG_USER=finproj
      - PG_PASS=finproj
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SUPERUSER_EMAIL=admin@admin.com
      - SUPERUSER_PASSWORD=admin
      - VK_ID=id
      - VK_SECRET=xxx
      - VK_KEY=xxx

  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379

  celery:
    build: .
    restart: always
    entrypoint: celery
    command: -A mymazon.celery worker -l INFO
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: finproj
      POSTGRES_PASSWORD: finproj
      POSTGRES_DB: finproj

