version: "3.8"

services:
  web:
    build: .
    restart: always
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - EMAIL_PASSWORD=werylongemailpass123
      - DBHOST=db

  redis:
    restart: always
    image: redis
    ports:
      - 6379:6379


  celery:
    build: .
    restart: always
    entrypoint: celery
    command: -A mymazon.celery worker -l INFO -P eventlet
    depends_on:
      - redis

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: finproj
      POSTGRES_PASSWORD: finproj
      POSTGRES_DB: finproj

